import { Geist, Geist_Mono,Inter,Raleway } from "next/font/google";
import "./globals.css";
import Navbar from "../../component/Navbar";
import Footer from "../../component/Footer";



const inter = Inter({
  subsets: ["latin"], 
  weight: ["400", "500", "600", "700"], 
  variable: "--font-inter", 
});
const raleway = Raleway({
  subsets: ["latin"], 
  weight: ["400", "500", "600", "700"], 
  variable: "--font-raleway", 
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Master & Dynamic",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${raleway.variable} antialiased`}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
