// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_slides: dynamic(() => import("./AboutSlides")),
  checkout_form: dynamic(() => import("./CheckoutForm")),
  compare_products: dynamic(() => import("./CompareProducts")),
  ear_phone: dynamic(() => import("./EarPhone")),
  empty_state: dynamic(() => import("./Cart")),
  feature_media_grid: dynamic(() => import("./FeatureMediaGrid")),
  form_request: dynamic(() => import("./FormRequest")),
  head_phones: dynamic(() => import("./HeadPhones")),
  headings: dynamic(() => import("./Headings")),
  hero_carousel: dynamic(() => import("./HeroCarousel")),
  highlighted_grid: dynamic(() => import("./HighlightedGrid")),
  media_text_duo_grid: dynamic(() => import("./About")),
  navbar: dynamic(() => import("./Navbar")),
  newsletter_with_links_columns: dynamic(() => import("./Footer")),
  product_detail: dynamic(() => import("./ProductDetail")),
  product_feature1: dynamic(() => import("./ProductFeature1")),
  product_featured_list: dynamic(() => import("./ProductFeaturedList")),
  product_grid: dynamic(() => import("./ProductGrid")),
  support_grid: dynamic(() => import("./Support")),
  timeline: dynamic(() => import("./Timeline")),
};
